# CONSTANTES PARA USAR LOS SERVICIOS WEB
COUNTRY = "mexico"
API_KEY = "92bdb3c2a4dda9611bbc0c96ebb122d2"
METHOD_TOP_TRACKS = "geo.gettoptracks"
METHOD_TOP_ARTISTS = "geo.gettopartists"

# CONSTANTES PARA ACCEDER A LOS DATOS JSON
JSON_DATA_ROOT_KEY_TOP_ARTISTS = "topartists"
JSON_DATA_ROOT_KEY_TOP_TRACKS = "tracks"
JSON_DATA_KEY_TOP_ARTISTS = "artist"
JSON_DATA_KEY_TOP_TRACKS = "track"
